### ISSUE TITLE
Automatically populate citations/publications?

### ISSUE THREAD

**Issue by navidcy** [josuemtzmo/josuemtzmo.github.io#12]
I noticed that these are hard coded values.

https://github.com/josuemtzmo/josuemtzmo.github.io/blob/ac6b5dfc87ce5618d50c00ec4c5488f670bc2cf9/research.html#L64

https://github.com/josuemtzmo/josuemtzmo.github.io/blob/ac6b5dfc87ce5618d50c00ec4c5488f670bc2cf9/research.html#L69

There is a good chance they are always outdated, especially the citations entry. Could you automatically populate these from, e.g., Google Scholar?

**Comment by josuemtzmo** [comment]
There is no access to the Google Scholar API to pull the references, thus it's a bit hard to do it.

**Comment by navidcy** [comment]
Then perhaps consider removing it? Or just put a link to your Google scholar profile where people can get this info? My 2 cents. Fee free to close the issue.

**Comment by josuemtzmo** [comment]
Done, I've coded something to automatically update the citations! 😁

**Comment by navidcy** [comment]
I knew you would. Nice.
